import 'package:adoption_app/models/animal.dart';

var dummyAnimals = [
  Animal(
    name: 'Buddy',
    imageUrl:
        "https://thumbs.wbm.im/pw/medium/00fce3cf67ed714a4a56a7f04eb7ba81.avif",
    description:
        'Friendly and playful. Loves going for walks.Friendly and playful. Loves going for walks.',
    type: 'Dog',
    breed: 'boxer',
    age: 2,
    activityLevel: 'High',
    sex: "Male",
    health: "Healthy",
    availability: true,
  ),
  Animal(
    name: 'Whiskers',
    imageUrl:
        "https://thumbs.wbm.im/pw/medium/c530d2f2a8bb15c02b9083a91aa9297c.avif",
    description:
        'Calm and loves to nap. Great with kids.Calm and loves to nap. Great with kids.Calm and loves to nap. Great with kids.',
    type: 'Cat',
    breed: 'siamese',
    age: 3,
    activityLevel: 'Low',
    sex: "Female",
    health: "Healthy",
    availability: true,
  ),
  Animal(
    name: 'Kiwi',
    imageUrl:
        "https://thumbs.wbm.im/pw/medium/236a4a4788de7780e1acf3c938d55f72.avif",
    description: 'Colorful and energetic. Enjoys flying around.',
    type: 'Bird',
    breed: 'parrot',
    age: 1,
    activityLevel: 'Medium',
    sex: "Male",
    health: "Healthy",
    availability: true,
  ),
  Animal(
    name: 'Coco',
    imageUrl:
        "https://thumbs.wbm.im/pw/medium/a2d0eeed60b645d479daf1519e7cb908.avif",
    description: 'Energetic and playful. Loves fetch.',
    type: 'Dog',
    breed: 'beagle',
    age: 2,
    activityLevel: 'High',
    sex: "Female",
    health: "Healthy",
    availability: true,
  ),
  Animal(
    name: 'Doggo',
    imageUrl:
        "https://thumbs.wbm.im/pw/medium/66eff00b7ae6b80c3d150c90986feb2b.avif",
    description: 'Friendly and playful. Loves going for walks.',
    type: 'Dog',
    breed: 'poodle',
    age: 2,
    activityLevel: 'High',
    sex: "Female",
    health: "Healthy",
    availability: true,
  ),
  Animal(
    name: 'Katto',
    imageUrl:
        "https://images.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: 'Calm and loves to nap. Great with kids.',
    type: 'Cat',
    breed: 'bengal',
    age: 3,
    activityLevel: 'Low',
    sex: "Female",
    health: "Healthy",
    availability: true,
  ),
  Animal(
    name: 'BirbBoi',
    imageUrl:
        "https://cdn.pixabay.com/photo/2019/07/27/06/13/canary-4365999_1280.jpg",
    description: 'Colorful and energetic. Enjoys flying around.',
    type: 'Bird',
    breed: 'canary',
    age: 14,
    activityLevel: 'Low',
    sex: "Male",
    health: "Healthy",
    availability: true,
  ),
  Animal(
    name: 'BirbGirl',
    imageUrl:
        "https://cdn.pixabay.com/photo/2018/02/14/20/16/red-factor-canary-3153848_1280.jpg",
    description: 'Colorful and energetic. Enjoys flying around.',
    type: 'Bird',
    breed: 'canary',
    age: 14,
    activityLevel: 'Low',
    sex: "Female",
    health: "Healthy",
    availability: true,
  ),
  Animal(
    name: 'OldBoi',
    imageUrl:
        "https://thumbs.wbm.im/pw/medium/b66db617446ee4a168075aeaaaef013a.avif",
    description: 'Energetic and playful. Loves fetch.',
    type: 'Dog',
    breed: 'boxer',
    age: 16,
    activityLevel: 'High',
    sex: "Female",
    health: "Healthy",
    availability: true,
  ),
  Animal(
    name: 'Blub',
    imageUrl:
        "https://cdn.pixabay.com/photo/2015/12/01/09/13/goldfish-1071839_1280.jpg",
    description: 'Is fish.',
    type: 'Fish',
    breed: 'goldfish',
    age: 9,
    activityLevel: 'Low',
    sex: "Female",
    health: "Healthy",
    availability: true,
  ),
  Animal(
    name: 'Bunni',
    imageUrl:
        "https://cdn.pixabay.com/photo/2020/02/29/18/59/rabbit-4890861_1280.jpg",
    description: 'Adorable and energetic. Loves hopping around.',
    type: 'Rodent',
    breed: 'Rabbit',
    age: 1,
    activityLevel: 'Medium',
    sex: "Female",
    health: "Healthy",
    availability: true,
  ),
  Animal(
    name: 'Piggo',
    imageUrl:
        "https://cdn.pixabay.com/photo/2014/01/11/23/40/guinea-pig-242520_1280.jpg",
    description: 'Sweet and sociable. Enjoys cuddling and nibbling on veggies.',
    type: 'Rodent',
    breed: 'guineaPig',
    age: 1,
    activityLevel: 'Low',
    sex: "Male",
    health: "Healthy",
    availability: true,
  ),
  Animal(
    name: 'Nibbles',
    imageUrl:
        "https://cdn.pixabay.com/photo/2016/10/26/22/00/hamster-1772742_1280.jpg",
    description: 'Tiny and curious. Loves running on the wheel.',
    type: 'Rodent',
    breed: 'Hamster',
    age: 5,
    activityLevel: 'High',
    sex: "Female",
    health: "Healthy",
    availability: true,
  ),
  Animal(
    name: 'Shadow',
    imageUrl:
        "https://media.istockphoto.com/id/1363808491/photo/the-rat-hides-under-wooden-planks-and-looks-out.jpg?s=2048x2048&w=is&k=20&c=rIGxAqr1b7k8c9Lm8FCZYoJgqDTUWq5QJS5ALOuma1g=",
    description: 'Intelligent and social. Enjoys climbing and snuggling.',
    type: 'Rodent',
    breed: 'Mice',
    age: 2,
    activityLevel: 'Medium',
    sex: "Male",
    health: "Healthy",
    availability: true,
  ),
  Animal(
    name: 'Ratto',
    imageUrl:
        "https://cdn.pixabay.com/photo/2016/03/05/18/54/animal-1238228_1280.jpg",
    description: 'Intelligent and social. Enjoys climbing and snuggling.',
    type: 'Rodent',
    breed: 'Rat',
    age: 7,
    activityLevel: 'High',
    sex: "Male",
    health: "Healthy",
    availability: true,
  )
];
