import 'package:adoption_app/models/animal.dart';

var dummyAnimals = [
  Animal(
      name: 'Buddy',
      imageUrl:
          "https://nebulae-assets.s3.amazonaws.com/3b56d17152bd46c295797a7eaab1f244.jpg",
      description:
          'Friendly and playful. Loves going for walks.Friendly and playful. Loves going for walks.',
      type: 'Dog',
      breed: 'boxer',
      age: 2,
      activityLevel: 'High',
      sex: "Male",
      health: "",
      availability: true,
      location: "Spjelkavik, Ålesund"),
  Animal(
      name: 'Whiskers',
      imageUrl:
          "https://nebulae-assets.s3.amazonaws.com/3b56d17152bd46c295797a7eaab1f244.jpg",
      description:
          'Calm and loves to nap. Great with kids.Calm and loves to nap. Great with kids.Calm and loves to nap. Great with kids.',
      type: 'Cat',
      breed: 'siamese',
      age: 3,
      activityLevel: 'Low',
      sex: "Female",
      health: "",
      availability: true,
      location: "Spjelkavik, Ålesund"),
  Animal(
      name: 'Kiwi',
      imageUrl:
          "https://nebulae-assets.s3.amazonaws.com/3b56d17152bd46c295797a7eaab1f244.jpg",
      description: 'Colorful and energetic. Enjoys flying around.',
      type: 'Bird',
      breed: 'parrot',
      age: 1,
      activityLevel: 'Medium',
      sex: "Male",
      health: "",
      availability: true,
      location: "Spjelkavik, Ålesund"),
  Animal(
      name: 'Coco',
      imageUrl:
          "https://nebulae-assets.s3.amazonaws.com/3b56d17152bd46c295797a7eaab1f244.jpg",
      description: 'Energetic and playful. Loves fetch.',
      type: 'Dog',
      breed: 'beagle',
      age: 2,
      activityLevel: 'High',
      sex: "Female",
      health: "",
      availability: true,
      location: "Spjelkavik, Ålesund"),
  Animal(
      name: 'Doggo',
      imageUrl:
          "https://nebulae-assets.s3.amazonaws.com/3b56d17152bd46c295797a7eaab1f244.jpg",
      description: 'Friendly and playful. Loves going for walks.',
      type: 'Dog',
      breed: 'poodle',
      age: 2,
      activityLevel: 'High',
      sex: "Female",
      health: "",
      availability: true,
      location: "Spjelkavik, Ålesund"),
  Animal(
      name: 'Katto',
      imageUrl:
          "https://nebulae-assets.s3.amazonaws.com/3b56d17152bd46c295797a7eaab1f244.jpg",
      description: 'Calm and loves to nap. Great with kids.',
      type: 'Cat',
      breed: 'bengal',
      age: 3,
      activityLevel: 'Low',
      sex: "Female",
      health: "",
      availability: true,
      location: "Spjelkavik, Ålesund"),
  Animal(
      name: 'BirbBoi',
      imageUrl:
          "https://nebulae-assets.s3.amazonaws.com/3b56d17152bd46c295797a7eaab1f244.jpg",
      description: 'Colorful and energetic. Enjoys flying around.',
      type: 'Bird',
      breed: 'canary',
      age: 14,
      activityLevel: 'Low',
      sex: "Male",
      health: "",
      availability: true,
      location: "Spjelkavik, Ålesund"),
  Animal(
      name: 'BirbGirl',
      imageUrl:
          "https://nebulae-assets.s3.amazonaws.com/3b56d17152bd46c295797a7eaab1f244.jpg",
      description: 'Colorful and energetic. Enjoys flying around.',
      type: 'Bird',
      breed: 'canary',
      age: 14,
      activityLevel: 'Low',
      sex: "Female",
      health: "",
      availability: true,
      location: "Spjelkavik, Ålesund"),
  Animal(
      name: 'OldBoi',
      imageUrl:
          "https://nebulae-assets.s3.amazonaws.com/3b56d17152bd46c295797a7eaab1f244.jpg",
      description: 'Energetic and playful. Loves fetch.',
      type: 'Dog',
      breed: 'boxer',
      age: 16,
      activityLevel: 'High',
      sex: "Female",
      health: "",
      availability: true,
      location: "Spjelkavik, Ålesund"),
  Animal(
      name: 'Blub',
      imageUrl:
          "https://nebulae-assets.s3.amazonaws.com/3b56d17152bd46c295797a7eaab1f244.jpg",
      description: 'Is fish.',
      type: 'Fish',
      breed: 'goldfish',
      age: 9,
      activityLevel: 'Low',
      sex: "Female",
      health: "",
      availability: true,
      location: "Spjelkavik, Ålesund"),
  Animal(
      name: 'Bunni',
      imageUrl:
          "https://nebulae-assets.s3.amazonaws.com/3b56d17152bd46c295797a7eaab1f244.jpg",
      description: 'Adorable and energetic. Loves hopping around.',
      type: 'Rodent',
      breed: 'Rabbit',
      age: 1,
      activityLevel: 'Medium',
      sex: "Female",
      health: "",
      availability: true,
      location: "Spjelkavik, Ålesund"),
  Animal(
      name: 'Piggo',
      imageUrl:
          "https://nebulae-assets.s3.amazonaws.com/3b56d17152bd46c295797a7eaab1f244.jpg",
      description:
          'Sweet and sociable. Enjoys cuddling and nibbling on veggies.',
      type: 'Rodent',
      breed: 'guineaPig',
      age: 1,
      activityLevel: 'Low',
      sex: "Male",
      health: "",
      availability: true,
      location: "Spjelkavik, Ålesund"),
  Animal(
      name: 'Nibbles',
      imageUrl:
          "https://nebulae-assets.s3.amazonaws.com/3b56d17152bd46c295797a7eaab1f244.jpg",
      description: 'Tiny and curious. Loves running on the wheel.',
      type: 'Rodent',
      breed: 'Hamster',
      age: 5,
      activityLevel: 'High',
      sex: "Female",
      health: "",
      availability: true,
      location: "Spjelkavik, Ålesund"),
  Animal(
      name: 'Shadow',
      imageUrl:
          "https://nebulae-assets.s3.amazonaws.com/3b56d17152bd46c295797a7eaab1f244.jpg",
      description: 'Intelligent and social. Enjoys climbing and snuggling.',
      type: 'Rodent',
      breed: 'Mice',
      age: 2,
      activityLevel: 'Medium',
      sex: "Male",
      health: "",
      availability: true,
      location: "Spjelkavik, Ålesund"),
  Animal(
      name: 'Ratto',
      imageUrl:
          "https://nebulae-assets.s3.amazonaws.com/3b56d17152bd46c295797a7eaab1f244.jpg",
      description: 'Intelligent and social. Enjoys climbing and snuggling.',
      type: 'Rodent',
      breed: 'Rat',
      age: 7,
      activityLevel: 'High',
      sex: "Male",
      health: "",
      availability: true,
      location: "Spjelkavik, Ålesund"),
];
