name: adoption_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  riverpod: ^2.4.8
  sign_in_button: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
 uses-material-design: true
 assets:
   - assets/images/petAdoptLogo.png

