name: adoption_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  intl: ^0.18.1
  flutter_riverpod: ^2.4.8
  sign_in_button: ^3.2.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/petAdoptLogo.png
