// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs7xuG9hWY5riODEzxI7piAj_ikBqvsLY',
    appId: '1:244927801410:web:db094110c552ff9f2725db',
    messagingSenderId: '244927801410',
    projectId: 'adoption-app-59977',
    authDomain: 'adoption-app-59977.firebaseapp.com',
    storageBucket: 'adoption-app-59977.appspot.com',
    measurementId: 'G-GXV0LSMR75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPAVdZeGijDeWPn11nraoyMlDYmSv8C8o',
    appId: '1:244927801410:android:a448999d91c897c72725db',
    messagingSenderId: '244927801410',
    projectId: 'adoption-app-59977',
    storageBucket: 'adoption-app-59977.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnPde4HyPqC2eyk2iaXaXMph85zX5n8HE',
    appId: '1:244927801410:ios:42ecc96d883140682725db',
    messagingSenderId: '244927801410',
    projectId: 'adoption-app-59977',
    storageBucket: 'adoption-app-59977.appspot.com',
    iosBundleId: 'com.example.adoptionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnPde4HyPqC2eyk2iaXaXMph85zX5n8HE',
    appId: '1:244927801410:ios:b8e6c23f0fd466bc2725db',
    messagingSenderId: '244927801410',
    projectId: 'adoption-app-59977',
    storageBucket: 'adoption-app-59977.appspot.com',
    iosBundleId: 'com.example.adoptionApp.RunnerTests',
  );
}
